"""empty message

Revision ID: b28da058bdfe
Revises: b8ad31739c09
Create Date: 2019-07-06 16:30:15.809365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28da058bdfe'
down_revision = 'b8ad31739c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('cds', sa.Integer(), nullable=True))
    op.add_column('album', sa.Column('lps', sa.Integer(), nullable=True))
    op.add_column('album', sa.Column('tapes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'tapes')
    op.drop_column('album', 'lps')
    op.drop_column('album', 'cds')
    # ### end Alembic commands ###
